language: go
sudo: false
before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/Masterminds/glide
- glide install
go:
- 1.6
env:
  matrix:
  - PORT=8080 IP=0.0.0.0
script:
- gocov test $(glide nv) | gocov report
notifications:
  slack:
    on_start: never
    email: false
    rooms:
      secure: LrSQIts9yze5iXAKkn9w8Ll+pXPpTKOXQfk+FUFFvk2ct/zAgUzfyUlATXkerMHlkyAVCOKFmoC5CKTs4FHnZJ+LvoYWjV7GGyFCt6y/28seW/IyVXUqjjG1S3AZJtMB2A1ItRP35+355+21wDbEqn+x/3Vi3BGwyUnaWdRxfLLZ96PH0gjfx2Ne1kbf4vSAv7I7G6l3K4ViJ/qGfZvw1n9mEvB+iqWEXuLEAoV9hjt8QphYSOYJXAVb42tmAwbJXNxwrRRyfIscKrxvYVsZtO6lflOqspFSnU6s9tq8sZM3RHSxdK2/ADEfZF1FQ7rxmv2flpSzYFOI5vAIqliyuWzDqNEUhbyFIrWA/Qsvc7gYrt7AjddWNKtuhTCGJ1dd11cLCZyzY4XLCveDLxktOUtOO50Bd7h6k4Kfpw8upXUzQYpuR4NcJEw0zjqkWYViMdl9I/DGp1FV7AdrsGvkA2nr6lB9H34R3hpXjvjW6YzzIDDTLYjzIRNAdD6F7Qjue2uYKQc7Un59WSaA+GgBwxMJhZVCyxkh7kg68HTLJzbORbtuh6TX0Ltc1ivPxxv1tFLaq4WwhCgNcznTY63kUQ6wHqgXzXj6zcwzdPNogTDSK/RnDgsRDTGw71qd4wYeKbVGcVcz6iGOAkA7hutraHZdjZOHQJ7M96SNcpGwbA4=
