language: go
sudo: false
before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/Masterminds/glide
- glide install
go:
- 1.6
env:
  matrix:
  - PORT=8080 IP=0.0.0.0
script:
- gocov test $(glide nv) | gocov report
notifications:
  slack:
    on_start: never
    email: false
    rooms:
      secure: wZOF4zsV5/j1YswHCd9erNqibvG2cteon7xJUd2g36EoXtanS9ByzMPaAy05ANHKmW6WxbX1hExtaHVV2o7PE+aO+BJTLI/gzhVrb9AEqLCO+JOou9XLr1DUctUethiFIVV2L5mp+8e1e7ELFc/ov6oyhZAVH5fjzEkHHxppDj/HujOTQqINxHN4p0IPcR/zAJKoAcGebzRhDK0Bpz40BbwTnawL2rrxMH8bkUuH+R6OiyrzoIjwWfUbUXkYfdUDF6W26WsChvaGsRehLM88uqVOK9HMSn4rzVOszFCmZ+TQW3dX+ZrZd0GXeCYBHn97nAtuehqLxx10rCSwqS4S5YfTmX0SlMX50iYsAczEDPDP9AIPBzcyiDBRK6iqxesex5wz/BaTjz1Vt8EEuSoL1I1tQRcmZgmuEJtt2hgaJmkJxAyd0rdQZsaQ4DcFwYDNmwSTsr9e2YmVqmJwMdrdam3mCrB62X11RNAROH0I+1dqNZ7OV0zNqlw3chqiXy3mUEK6zruoB05Cs9xtG/UpSd/AhIJey1JTTpXyxc0FEDgx7vDX5ipLxIIP8Y+pvq8RUcyfZNZpLS83WpRYPAPOiS/DUmKon4nbTFI6K3ka1xfpkOHKubBRycRJi69uEUN4YzmafRB5xZ6zu9SIBKr3oQz6iA3auyG1DbMn5sA5ttE=
